### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by KyleTryon** [autifyhq/autify-circleci-orb-web#4]
Hello Autify team,

I am from the @CircleCI Community and Partner Engineering team, here to help with a review for CircleCI orb partnership. I have a few items listed below for changes:

1. Move documentation out of the description
  a. The description of the orb is used for SEO purposes. Documentation should be listed within the orb itself via parameters.
  b. Consider making your homepage link, a link to further documentation for this integration hosted on your website.
1. Add a parameter for API tokens
  a. As per [best practices](https://circleci.com/docs/2.0/orb-author-faq/#secure-api-tokens), API tokens should be parameterized, so the user may if needed, provide an alternate environment variable.
  b. Having the token parameterized, also gives you as the developer a chance to document this in the parameter description.
  c. Here is an example:
    1. YAML: https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/commands/setup.yml#L11
    2. BASH: https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/scripts/configure.sh#L3
 1. Last just a request/question. What type of information is returned from these tests? Could the data be returned to CircleCI in JUNIT? If yes, we can display information about these results visually in our UI.
 
 Please let us know if you have any questions.

**Comment by riywo** [comment]
@KyleTryon I have updated the Orb. (Note: I renamed the Orb)

1. Fixed. https://circleci.com/developer/orbs/orb/autify/autify-web
2. Fixed. https://circleci.com/developer/orbs/orb/autify/autify-web
3. We don't provide JUnit type of output yet. We can just provide a URL to the test result on our website.
